# Generated by Django 4.2.3 on 2024-09-19 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_submission_quastion_choice_quastion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quastion',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='quastion',
            new_name='question',
        ),
    ]
